#!/bin/sh
set -e

if test "$#" -lt 3 -o "$#" -gt 4 ; then
	echo "Usage: $0 TYPE OUTFILE KERNEL [INITRAMFS]"
	exit 1
fi

TYPE="$1"
OUTFILE="$2"
KERNEL="$3"
INITRAMFS="$4"

if test -z "$INITRAMFS" ; then
	INITRAMFS="$(mktemp)"
	DUMMY_INITRAMFS=1
fi

BOOTIMG="$(mktemp)"
mkbootimg --kernel "$KERNEL" --ramdisk "$INITRAMFS" -o "$BOOTIMG"

if test "$DUMMY_INITRAMFS" = 1 ; then
	rm "$INITRAMFS"
fi

if test "$TYPE" = 'nand' ; then
	cc-mangle-bootimg "$BOOTIMG" "$OUTFILE" 0x2
elif test "$TYPE" = 'usb' ; then
	cc-mangle-bootimg "$BOOTIMG" "$OUTFILE" 0x82
else
	echo "TYPE must be either \"usb\" or \"nand\""
fi

rm "$BOOTIMG"
