#!/bin/sh
set -e

if test "$#" -ne 4 ; then
	echo "Usage: $0 TYPE OUTFILE KERNEL INITRAMFS_DIR"
	exit 1
fi

TYPE="$1"
OUTFILE="$2"
KERNEL="$3"
INITRAMFS_DIR="$4"

INITRAMFS="$(mktemp)"
pushd "$INITRAMFS_DIR" >/dev/null
find . | cpio -o -H newc 2>/dev/null | gzip > "$INITRAMFS"
popd >/dev/null

BOOTIMG="$(mktemp)"
cc-make-bootimg "$TYPE" "$OUTFILE" "$KERNEL" "$INITRAMFS"

rm "$INITRAMFS"
