#!/bin/sh
set -e

if test "$#" -ne 3 ; then
	echo "Usage: $0 OUTFILE KERNEL INITRAMFS_DIR"
	exit 1
fi

OUTFILE="$1"
KERNEL="$2"
INITRAMFS_DIR="$3"

INITRAMFS="$(mktemp)"
pushd "$INITRAMFS_DIR" >/dev/null
find . | cpio -o -H newc 2>/dev/null | gzip > "$INITRAMFS"
popd >/dev/null

BOOTIMG="$(mktemp)"
cc-make-bootimg "$OUTFILE" "$KERNEL" "$INITRAMFS"

rm "$INITRAMFS"
